[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pywebexpo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pymc = ">=5.20.0,<6"
blackjax = ">=1.2.4,<2"
numpyro = ">=0.16.1,<0.17"
numpy = ">=1.26.4,<2"
jax = ">=0.4.35,<0.5"
nutpie = ">=0.13.2,<0.14"
numba = ">=0.60.0,<0.61"
pytest = ">=8.3.4,<9"
pyperf = ">=2.6.2,<3"
